
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE     24000
#define AUDIO_OUTPUT_SAMPLE_RATE    24000

#define AUDIO_I2S_GPIO_MCLK     GPIO_NUM_13
#define AUDIO_I2S_GPIO_WS       GPIO_NUM_10
#define AUDIO_I2S_GPIO_BCLK     GPIO_NUM_5
#define AUDIO_I2S_GPIO_DIN      GPIO_NUM_6
#define AUDIO_I2S_GPIO_DOUT     GPIO_NUM_9

#define AUDIO_CODEC_PA_PIN      GPIO_NUM_14
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_11
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_12
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_18
#define BOOT_BUTTON_GPIO        GPIO_NUM_4

#define POWER_KEY_BUTTON_GPIO   GPIO_NUM_NC
#define POWER_CTL_GPIO          GPIO_NUM_NC

#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_3
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_0
#define CHARGING_GPIO           GPIO_NUM_NC
#define DONE_GPIO               GPIO_NUM_NC

#define BATTERY_ADC_PIN         GPIO_NUM_1

#define DISPLAY_SPI_SCK_PIN     GPIO_NUM_39
#define DISPLAY_SPI_MOSI_PIN    GPIO_NUM_40
#define DISPLAY_DC_PIN          GPIO_NUM_38
#define DISPLAY_SPI_CS_PIN      GPIO_NUM_41
#define DISPLAY_RES             GPIO_NUM_45
#define DISPLAY_BLK             GPIO_NUM_42

#define DISPLAY_WIDTH       240
#define DISPLAY_HEIGHT      240
#define DISPLAY_SWAP_XY     false
#define DISPLAY_MIRROR_X    false
#define DISPLAY_MIRROR_Y    false
#define BACKLIGHT_INVERT    false

#define DISPLAY_OFFSET_X        0
#define DISPLAY_OFFSET_Y        0
#define DISPLAY_BACKLIGHT_PIN   GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define ML307_RX_PIN GPIO_NUM_12
#define ML307_TX_PIN GPIO_NUM_13

#endif // _BOARD_CONFIG_H_
